### ISSUE TITLE
Error while building stub

### ISSUE THREAD

**Issue by nzyuko** [Amaop/Rust-Crypter#1]
Compiling memexec v0.2.0
error[E0425]: cannot find value `IMAGE_REL_BASED` in this scope
  --> /home/kali/.cargo/registry/src/github.com-1ecc6299db9ec823/memexec-0.2.0/src/peloader/mod.rs:38:36
   |
38 |                 if (item >> 12) == IMAGE_REL_BASED {
   |                                    ^^^^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `IMAGE_THUNK_DATA` in this scope
  --> /home/kali/.cargo/registry/src/github.com-1ecc6299db9ec823/memexec-0.2.0/src/peloader/mod.rs:80:79
   |
80 |                     base_addr.offset(import_desc.FirstThunk as isize) as *mut IMAGE_THUNK_DATA,
   |                                                                               ^^^^^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `IMAGE_THUNK_DATA` in this scope
  --> /home/kali/.cargo/registry/src/github.com-1ecc6299db9ec823/memexec-0.2.0/src/peloader/mod.rs:82:35
   |
82 |                         as *const IMAGE_THUNK_DATA,
   |                                   ^^^^^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `IMAGE_THUNK_DATA` in this scope
  --> /home/kali/.cargo/registry/src/github.com-1ecc6299db9ec823/memexec-0.2.0/src/peloader/mod.rs:86:79
   |
86 |                     base_addr.offset(import_desc.FirstThunk as isize) as *mut IMAGE_THUNK_DATA,
   |                                                                               ^^^^^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `IMAGE_THUNK_DATA` in this scope
  --> /home/kali/.cargo/registry/src/github.com-1ecc6299db9ec823/memexec-0.2.0/src/peloader/mod.rs:87:81
   |
87 |                     base_addr.offset(import_desc.FirstThunk as isize) as *const IMAGE_THUNK_DATA,
   |                                                                                 ^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `IMAGE_ORDINAL_FLAG` in this scope
  --> /home/kali/.cargo/registry/src/github.com-1ecc6299db9ec823/memexec-0.2.0/src/peloader/mod.rs:97:33
   |
97 |                 if thunk_data & IMAGE_ORDINAL_FLAG != 0 {
   |                                 ^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `IMAGE_THUNK_DATA` in this scope
   --> /home/kali/.cargo/registry/src/github.com-1ecc6299db9ec823/memexec-0.2.0/src/peloader/mod.rs:119:45
    |
119 |                     *iat_ptr = proc_addr as IMAGE_THUNK_DATA;
    |                                             ^^^^^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `IMAGE_THUNK_DATA` in this scope
   --> /home/kali/.cargo/registry/src/github.com-1ecc6299db9ec823/memexec-0.2.0/src/peloader/mod.rs:153:45
    |
153 |                     *iat_ptr = proc_addr as IMAGE_THUNK_DATA;
    |                                             ^^^^^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `IMAGE_TLS_DIRECTORY` in this scope
   --> /home/kali/.cargo/registry/src/github.com-1ecc6299db9ec823/memexec-0.2.0/src/peloader/mod.rs:169:60
    |
169 |         let tls = &*mem::transmute::<*const c_void, *const IMAGE_TLS_DIRECTORY>(
    |                                                            ^^^^^^^^^^^^^^^^^^^
    |
   ::: /home/kali/.cargo/registry/src/github.com-1ecc6299db9ec823/memexec-0.2.0/src/peparser/def.rs:84:9
    |
84  |         pub struct $name {
    |         ---------------- similarly named struct `IMAGE_TLS_DIRECTORY32` defined here
    |
help: a struct with a similar name exists
    |
169 |         let tls = &*mem::transmute::<*const c_void, *const IMAGE_TLS_DIRECTORY32>(
    |                                                            ~~~~~~~~~~~~~~~~~~~~~
help: you might be missing a type parameter
    |
166 | unsafe fn call_tls_callback<IMAGE_TLS_DIRECTORY>(pe: &PE, base_addr: *const c_void) -> Result<()> {
    |                            +++++++++++++++++++++

Some errors have detailed explanations: E0412, E0425.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `memexec` due to 9 previous errors

**Comment by Kerneldrop** [comment]
can you show me your cargo build command that you used please?

**Comment by nzyuko** [comment]
cargo build --release

**Comment by Kerneldrop** [comment]
try this mate, `cargo build --target x86_64-pc-windows-gnu --release` 
youre building on kali so cargo is defaulting to linux, this should work

**Comment by nzyuko** [comment]
yeah this fixed it thanks
